sudo: false
language: node_js
node_js:
  - 12 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - hexo-dev # build hexo-dev branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  target_branch: master
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: hexo-dev
  local-dir: public